# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AKlever(object):
    def setupUi(self, AKlever):
        AKlever.setObjectName("AKlever")
        AKlever.resize(854, 306)
        self.centralwidget = QtWidgets.QWidget(AKlever)
        self.centralwidget.setMinimumSize(QtCore.QSize(849, 306))
        self.centralwidget.setMaximumSize(QtCore.QSize(849, 306))
        self.centralwidget.setObjectName("centralwidget")
        self.startData = QtWidgets.QListWidget(self.centralwidget)
        self.startData.setGeometry(QtCore.QRect(0, 0, 271, 271))
        self.startData.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startData.setObjectName("startData")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(280, 0, 571, 218))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.answer1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.answer1.setEnabled(False)
        self.answer1.setObjectName("answer1")
        self.horizontalLayout_4.addWidget(self.answer1)
        self.probab1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.probab1.setMaximumSize(QtCore.QSize(64, 32))
        self.probab1.setAlignment(QtCore.Qt.AlignCenter)
        self.probab1.setObjectName("probab1")
        self.horizontalLayout_4.addWidget(self.probab1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.answer3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.answer3.setEnabled(False)
        self.answer3.setObjectName("answer3")
        self.horizontalLayout.addWidget(self.answer3)
        self.probab3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.probab3.setMaximumSize(QtCore.QSize(64, 32))
        self.probab3.setAlignment(QtCore.Qt.AlignCenter)
        self.probab3.setObjectName("probab3")
        self.horizontalLayout.addWidget(self.probab3)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.answer2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.answer2.setEnabled(False)
        self.answer2.setObjectName("answer2")
        self.horizontalLayout_3.addWidget(self.answer2)
        self.probab2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.probab2.setMaximumSize(QtCore.QSize(64, 32))
        self.probab2.setAlignment(QtCore.Qt.AlignCenter)
        self.probab2.setObjectName("probab2")
        self.horizontalLayout_3.addWidget(self.probab2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.question = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.question.setEnabled(False)
        self.question.setMaximumSize(QtCore.QSize(16777215, 32))
        self.question.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.question.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.question.setReadOnly(True)
        self.question.setCenterOnScroll(True)
        self.question.setObjectName("question")
        self.gridLayout.addWidget(self.question, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 280, 851, 23))
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.updateButton = QtWidgets.QToolButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(230, 230, 36, 36))
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 220, 571, 54))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.startBtn.setFont(font)
        self.startBtn.setCheckable(False)
        self.startBtn.setAutoDefault(False)
        self.startBtn.setDefault(False)
        self.startBtn.setFlat(False)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_2.addWidget(self.startBtn)
        self.stopBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stopBtn.setFont(font)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_2.addWidget(self.stopBtn)
        AKlever.setCentralWidget(self.centralwidget)

        self.retranslateUi(AKlever)
        QtCore.QMetaObject.connectSlotsByName(AKlever)

    def retranslateUi(self, AKlever):
        _translate = QtCore.QCoreApplication.translate
        AKlever.setWindowTitle(_translate("AKlever", "AKlever"))
        self.answer1.setText(_translate("AKlever", "Answer 1"))
        self.probab1.setText(_translate("AKlever", "%"))
        self.answer3.setText(_translate("AKlever", "Answer 3"))
        self.probab3.setText(_translate("AKlever", "%"))
        self.answer2.setText(_translate("AKlever", "Answer 2"))
        self.probab2.setText(_translate("AKlever", "%"))
        self.question.setPlainText(_translate("AKlever", "вопрос"))
        self.progressBar.setFormat(_translate("AKlever", "TIME"))
        self.updateButton.setText(_translate("AKlever", "UPD"))
        self.startBtn.setText(_translate("AKlever", "START"))
        self.stopBtn.setText(_translate("AKlever", "STOP"))

