WEBSOCKET_NOT_INSTALLED = "WebSocket module is not installed. VVP, HQ and CS won't be available."
NO_ACCOUNT = "No account"
CHECKING_FOR_UPDATES = "Checking for updates..."
CHECKING_FOR_UPDATES_FAILED = "Unable to check for updates. Current version is %s"
NEW_VERSION_AVAILABLE = "New version is available, would you like to auto-update?"
EXE_NOT_YET_COMPILED = "It seems that you are using .exe version of bot, and latest version is not yet compiled.\nCan't proceed."
UPDATE_FAILED = "Oops, something went wrong. Can't proceed. Error code %s"
CONFIGURATION_INTRO = "Configurating %s. Choose option to edit from list below:"
DEBUG_MODE = "Debug mode"
VK_AUTH_TOKEN = "VK auth token"
CHECK_FOR_UPDATES = "Check for updates"
TELEGRAM_INTEGRATION = "Telegram integration"
ANSWER_UI = "Answer UI"
LANGUAGE = "Language"
SAVE_AND_EXIT = "Save and exit"
EDITED = "[EDITED]"
DEBUG_DISABLED = "Disabled - only log critical exceptions"
DEBUG_BASIC = "Basic - log some information"
DEBUG_VERBOSE = "Verbose - log basically everything"
BACK = "Back"
VK_AUTH_INFO = "To use bot for VK Clever you need VK access token."
CURRENT_TOKEN = "Current token"
CURRENT_ACCOUNT = "Current account"
CHANGE_TOKEN = "Change token"
UPDATES_INFO = "It is not recommended to disable update check"
ENABLE = "Enable"
DISABLE = "Disable"
TELEGRAM_INTEGRATION_INFO = "Since 0.90 %s supports Telegram integration"
TELEGRAM_BOT_TOKEN = "Bot token"
TELEGRAM_CHANNEL = "Channel to post"
PROXY = "Proxy"
TELEGRAM_AUTO_SEND = "Auto send to channel"
TELEGRAM_ENABLE_DISABLE = "Enable or disable Telegram integration"
TELEGRAM_BOT_TOKEN_INFO = "To use Telegram integration you need a Bot token.\nTo get it message @BotFather and register a bot"
ENTER_YOUR_TOKEN = "Enter your token"
TELEGRAM_CHANNEL_INFO = "For %s to work correctly, we need to know to which channel/group to post.\nYour bot must be admin in this channel/group with rights to post messages"
ENTER_YOUR_CHANNEL = "Enter your channel/group"
CHANGE_CHANNEL = "Change channel/group"
TELEGRAM_PROXY_INFO = "In several countries, some providers (try to) block Telegram API server, so\nyou may need a SOCKS5 proxy to connect"
SET_PROXY = "Set proxy"
ENTER_YOUR_PROXY = "Enter you proxy in this format: [login[:password]@]server.tld[:port]"
TELEGRAM_AUTO_SEND_INFO = "Enable or disable auto answer sending (only if answer ui is enabled)"
ANSWER_UI_INFO = "Enable or disable answer UI"
LANGUAGE_INFO = "Since 0.95 %s supports multiple languages"
CUSTOM_QUESTION_INFO = "Enter question in this format:"
CUSTOM_QUESTION_FORMAT = "question:answer1#answer2[#answer3[...]]"
MALFORMED_INPUT = "Malformed input, cancelling"
GETTING_DATA = "Getting data...      "
GETTING_TOKEN = "Getting token...    "
YOUR_STATS = "======={ YOUR STATS }======="
BALANCE = "BALANCE:\t\t"
EXTRA_LIVES = "EXTRA LIVES:\t"
COINS = "COINS:\t\t\t"
RATING = "RATING (%):\t\t"
GAME_INFO = "======={ GAME  INFO }======="
NEXT_GAME = "NEXT GAME:\t\t"
NOW = "NOW!"
PRIZE = "PRIZE:\t\t\t"
STATE = "STATE:\t\t\t"
TO_STOP_PRESS = "To stop press Ctrl-C"
RECEIVED_QUESTION = "Received question, thinking..."
NO_QUESTION = "No question, waiting.."
BOT_INFO = "This is %s, bot for multiple trivias\nCoded by TaizoGem, source is available at:\ngithub.com/TaizoGem/AKlever\nCurrent version: %s"
BOT_COMMANDS = "\n\nAvailable commands:\n" \
              "?, h        - display this menu\n" \
              "run, start  - start working\n" \
              "auth        - re-auth in application\n" \
              "custom, c   - process a custom question\n" \
              "e, exit     - exit from application\n" \
              "vidinfo     - information about current video\n" \
              "config      - configure application"
QUESTION = "Question %s: %s"
ANSWER = "Answer"
ANSWER_FOR_QUESTION = "Answer for question %s: %s"
BOT_STATUS = "Bot status: "
CORRECT = "correct"
INCORRECT = "incorrect"
SOCKS_NOT_INSTALLED_FAIL = "Unable to send message because socks support is not installed"
ANSWER_UI_CONTINUE = "Continue"
ANSWER_UI_REGOOGLE = "Re-google"
ANSWER_UI_FORCE_REVERSE = "Force do reverse search"
ANSWER_UI_SEND_TELEGRAM = "Send to"
CLI_PROMPT = "[? for help] %s > "
INVALID_ACTION = "Invalid action, enter ? or h for help"
CURRENT_VIDEO = "Current video:"
GAME_IS_NOT_RUNNING_NOW = "Game is not running now, nothing to display!"
WHAT_BOT = "What bot would you like to start?"
CONFIG = "Configuration"
CUSTOM_QUESTION = "Custom question"
VK_CLEVER_NAME = "VK Clever"
VVP_NAME = "VVP"
Yn_PROMPT = "[Y/n] "
n_ARRAY = ("N", "n")
GAME_STATE_PLANNED_ = "Planned"
GAME_STATE_STARTED_ = "Started"
GAME_STATE_FINISHED_ = "Finished"
CURRENT_LANG = "English by TaizoGem"
EXIT = "Exit"
